[package]
name = "pymzpeaks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pymzpeaks"
crate-type = ["cdylib"]

[features]
serde-support = ["mzpeaks/serde-support"]

[dependencies]
pyo3 = "0.21.0"
mzpeaks = { path = "../../" }
